[package]
name = "nightcycle/geometry-util"
description = "A geometry util!"
version = "1.0.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]
